### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by DanielRuf** [diverent2/flagfinder#2]
- [X] Switch to GitHub Actions
- [ ] Add testing pipeline

**Comment by DanielRuf** [comment]
Hey @diverent2, did you already signup for the GitHub Actions beta at https://github.com/features/actions/signup/?account=diverent2?

**Comment by DanielRuf** [comment]
Hm, seems NOW does not find the project at https://zeit.co/diverent2/flagfinder/bvysuxye3

**Comment by diverent2** [comment]
Your PR was reviewed #5 and requires some changes.
It would be awesome if you could take a look at it 👍
