### ISSUE TITLE
On /search some texts overflow the flagCard

### ISSUE THREAD

**Issue by chomchom02** [diverent2/flagfinder#25]
# 🐞 bug report

On /search some texts overflow the flagCard

## Current behavior 👎

> **What's the current behavior?**

![c83eaf5f-b61a-4ae7-8562-be4be7c04eb9](https://user-images.githubusercontent.com/20092945/71075080-c4898280-2183-11ea-943d-dd945a00dc4a.jpg)

## Expected behavior 👍

> **What is the expected behavior?**

Text stay in card 

## Steps to reproduce

> **Please provide the steps to reproduce the bug and, if possible, a minimal demo of the problem**

1. Go to prideflags.info/search
2. Got the same screen resolution as me.

### Environment information 🖥️

> **Please tell us about your environment**

|                     | your environment     |
| ------------------- | -------------------- |
| Device              | SM-A600FN |
| OS and version      | Android 9  |
| Browser and Version | Chrome 79        |
| Display Size | 5,6 inches, 720x1480 pixels, 293 dpi        |

## Further information

> related issues, suggestions how to fix, links and examples, screenshots

**Comment by diverent2** [comment]
Solved through #20.
Thank you for your report!
