### ISSUE TITLE
Turn labels into search filter links

### ISSUE THREAD

**Issue by diverent2** [diverent2/flagfinder#28]
# 💡 feature request

## I would really like the project to

- redirect to a category filtered search when I click on a category label

### Expected Behavior

1. Click a label
2. Go back to search; active search: clicked label

## Reasons why this change would be good

> **use cases, advantages, necessity**

- improves UX
- corresponds with expected behavior

## Other information

> related issues, solution ideas, pull requests, screenshots, links and examples

<img width="412" alt="Bildschirmfoto 2019-12-28 um 20 43 54" src="https://user-images.githubusercontent.com/24892204/71548766-48791100-29b3-11ea-821e-0669f6d8582f.png">

**Comment by chomchom02** [comment]
This is obviously a duplicate. Please see #31.
