### ISSUE TITLE
/search reload [500 activeFilters.flat is not a function]

### ISSUE THREAD

**Issue by chomchom02** [diverent2/flagfinder#30]
# 🐞 bug report

## Current behavior 👎

When reloading the /search page, a page with the content "500 activeFilters.flat is not a function" appears for a few seconds (see screenshot). After that the expected page is shown. 

## Expected behavior 👍

1. reload page
2. get page

## Steps to reproduce

1. reload page
2. read text

### Environment information 🖥️

|                     | your environment     |
| ------------------- | -------------------- |
| Device              | Samsung Galaxy A6 (2018) (SM-A600FN) |
| OS and version      | Android V. 9 (API Level 28)  |
| Browser and Version | Chrome 79 (0.3945.93)       |

## Further information

![4e0b4240-a767-4011-a54e-d576017ef215](https://user-images.githubusercontent.com/20092945/71550895-de746200-29da-11ea-9576-628f0c685f45.jpg)

**Comment by diverent2** [comment]
Can no longer reproduce. WIll repopen, if the problem returns
